# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Estructura_principal_FINAL.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(871, 630)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 871, 651))
        self.widget_2.setObjectName("widget_2")
        self.frame_lateral_2 = QtWidgets.QFrame(self.widget_2)
        self.frame_lateral_2.setGeometry(QtCore.QRect(0, 0, 200, 601))
        self.frame_lateral_2.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_lateral_2.setMaximumSize(QtCore.QSize(0, 12000))
        self.frame_lateral_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_lateral_2.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 0, 0);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"\n"
"")
        self.frame_lateral_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lateral_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lateral_2.setObjectName("frame_lateral_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_lateral_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(10, 10, 120, 10)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        #self.bt_restaurar = QtWidgets.QPushButton(self.frame_lateral_2)
        #self.bt_restaurar.setMaximumSize(QtCore.QSize(16777215, 35))
        #self.bt_restaurar.setStyleSheet("QPushButton{\n"

        #self.bt_restaurar.setText("")
        #icon = QtGui.QIcon()
        #icon.addPixmap(QtGui.QPixmap("images/fullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        #self.bt_restaurar.setIcon(icon)
        #self.bt_restaurar.setObjectName("bt_restaurar")
        #self.horizontalLayout_6.addWidget(self.bt_restaurar)
        self.bt_close = QtWidgets.QPushButton(self.frame_lateral_2)
        self.bt_close.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bt_close.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"QPushButton#bt_close:pressed{\n"
"padding-left:1px;\n"
"padding-top:1px;\n"
"\n"
"}")
        self.bt_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("modules/images/cerca.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_close.setIcon(icon1)
        self.bt_close.setObjectName("bt_close")
        self.horizontalLayout_6.addWidget(self.bt_close)
        self.bt_minimizar = QtWidgets.QPushButton(self.frame_lateral_2)
        self.bt_minimizar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bt_minimizar.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"QPushButton#bt_minimizar:pressed{\n"
"padding-left:1px;\n"
"padding-top:1px;\n"
"\n"
"}")
        self.bt_minimizar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("modules/images/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_minimizar.setIcon(icon2)
        self.bt_minimizar.setObjectName("bt_minimizar")
        self.horizontalLayout_6.addWidget(self.bt_minimizar)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)

        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        font.setKerning(True)
        #self.bt_menu.setFont(font)
        #self.bt_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        #self.bt_menu.setAutoFillBackground(False)

        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("modules/images/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        #self.bt_menu.setIcon(icon4)
        #self.bt_menu.setIconSize(QtCore.QSize(15, 15))
        #self.bt_menu.setObjectName("bt_menu")
        #self.verticalLayout_7.addWidget(self.bt_menu)
        self.bt_inicio = QtWidgets.QPushButton(self.frame_lateral_2)
        self.bt_inicio.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_inicio.setMaximumSize(QtCore.QSize(16777215, 40))
        self.bt_inicio.setStyleSheet("QPushButton#bt_inicio:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(105, 118, 132, 200);\n"
"}\n"
"\n"
"QPushButton#bt_inicio:hover{\n"
"font:87 10pt \"Arial Black\";\n"
"background-color:white;\n"
"}\n"
"QPushButton#bt_inicio{\n"
"backgroud-color:#aa00ff;\n"
"font:87 10pt \"Arial Black\";\n"
"border-radius:15px;\n"
"text-align: left;\n"
"padding-left: 8px;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("modules/images/hogar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_inicio.setIcon(icon5)
        self.bt_inicio.setObjectName("bt_inicio")
        self.verticalLayout_7.addWidget(self.bt_inicio)
        self.bt_base_datos = QtWidgets.QPushButton(self.frame_lateral_2)
        self.bt_base_datos.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_base_datos.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.bt_base_datos.setFont(font)
        self.bt_base_datos.setStyleSheet("QPushButton#bt_base_datos:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(105, 118, 132, 200);\n"
"}\n"
"\n"
"QPushButton#bt_base_datos:hover{\n"
"font:87 10pt \"Arial Black\";\n"
"background-color:white;\n"
"}\n"
"QPushButton#bt_base_datos{\n"
"backgroud-color:#aa00ff;\n"
"font:87 10pt \"Arial Black\";\n"
"border-radius:15px;\n"
"text-align: left;\n"
"padding-left: 8px;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("modules/images/flecha-hacia-arriba.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_base_datos.setIcon(icon6)
        self.bt_base_datos.setObjectName("bt_base_datos")
        self.verticalLayout_7.addWidget(self.bt_base_datos)
        self.bt_list = QtWidgets.QPushButton(self.frame_lateral_2)
        self.bt_list.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_list.setMaximumSize(QtCore.QSize(16777215, 40))
        self.bt_list.setStyleSheet("QPushButton#bt_list:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(105, 118, 132, 200);\n"
"}\n"
"\n"
"QPushButton#bt_list:hover{\n"
"font:87 10pt \"Arial Black\";\n"
"background-color:white;\n"
"}\n"
"QPushButton#bt_list{\n"
"backgroud-color:#aa00ff;\n"
"font:87 10pt \"Arial Black\";\n"
"border-radius:15px;\n"
"text-align: left;\n"
"padding-left: 8px;\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("modules/images/flecha-hacia-abajo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_list.setIcon(icon7)
        self.bt_list.setObjectName("bt_list")
        self.verticalLayout_7.addWidget(self.bt_list)
        spacerItem = QtWidgets.QSpacerItem(20, 360, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.bt_config = QtWidgets.QPushButton(self.frame_lateral_2)
        self.bt_config.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_config.setMaximumSize(QtCore.QSize(16777215, 40))
        self.bt_config.setStyleSheet("QPushButton#bt_config:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(105, 118, 132, 200);\n"
"}\n"
"\n"
"QPushButton#bt_config:hover{\n"
"font:87 10pt \"Arial Black\";\n"
"background-color:white;\n"
"}\n"
"QPushButton#bt_config{\n"
"backgroud-color:#aa00ff;\n"
"font:87 10pt \"Arial Black\";\n"
"border-radius:15px;\n"
"text-align: left;\n"
"padding-left: 8px;\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("modules/images/configuraciones.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_config.setIcon(icon8)
        self.bt_config.setObjectName("bt_config")
        self.verticalLayout_7.addWidget(self.bt_config)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.widget_2)
        self.stackedWidget_2.setGeometry(QtCore.QRect(200, 0, 631, 601))
        self.stackedWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:15px;")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_tres = QtWidgets.QWidget()
        self.page_tres.setObjectName("page_tres")
        self.label_21 = QtWidgets.QLabel(self.page_tres)
        self.label_21.setGeometry(QtCore.QRect(210, 385, 221, 22))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color:red;")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        ###################
        self.label_22 = QtWidgets.QLabel(self.page_tres)
        self.label_22.setGeometry(QtCore.QRect(60, 400, 215, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color:red;")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        ###################
        self.label_23 = QtWidgets.QLabel(self.page_tres)
        self.label_23.setGeometry(QtCore.QRect(359, 400, 210, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color:red;")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")        
        ###################
        self.label_17 = QtWidgets.QLabel(self.page_tres)
        self.label_17.setGeometry(QtCore.QRect(200, 170, 231, 22))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color:red;")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        #############
        self.tabla = QtWidgets.QTableWidget(self.page_tres)
        self.tabla.setGeometry(QtCore.QRect(30, 420, 280, 180))
        self.tabla.setStyleSheet("QTableView {border: 1px solid black ;\n"
"background-color: white; color: black; }\n"
"QTableView::item { border-bottom: 1px solid black; border-right: 1px solid black;\n"
" height: 50px; width: 100px; \n"
"}\n"
"QHeaderView::section { background-color: gray; color: white; }\n"
"QTableView::item:selected { background-color: blue; color: white;    }")
        self.tabla.setObjectName("tabla")
        self.tabla.setColumnCount(0)
        self.tabla.setRowCount(0)

        #############
        self.tabla2 = QtWidgets.QTableWidget(self.page_tres)
        self.tabla2.setGeometry(QtCore.QRect(320, 420, 280, 180))
        self.tabla2.setStyleSheet("QTableView {border: 1px solid black ;\n"
"background-color: white; color: black; }\n"
"QTableView::item { border-bottom: 1px solid black; border-right: 1px solid black;\n"
" height: 50px; width: 100px; \n"
"}\n"
"QHeaderView::section { background-color: gray; color: white; }\n"
"QTableView::item:selected { background-color: blue; color: white;    }")
        self.tabla2.setObjectName("tabla2s")
        self.tabla2.setColumnCount(0)
        self.tabla2.setRowCount(0)        
        #############
        self.tableWidget = QtWidgets.QTableWidget(self.page_tres) 
        self.tableWidget.setGeometry(QtCore.QRect(30, 200, 570, 180))
        self.tableWidget.setStyleSheet("QTableView {border: 1px solid black ;\n"
"background-color: white; color: black; }\n"
"QTableView::item { border-bottom: 1px solid black; border-right: 1px solid black;\n"
" height: 50px; width: 100px; \n"
"}\n"
"QHeaderView::section { background-color: gray; color: white; }\n"
"QTableView::item:selected { background-color: blue; color: white;    }")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        #############
        self.label_19 = QtWidgets.QLabel(self.page_tres)
        self.label_19.setGeometry(QtCore.QRect(200, 20, 251, 23))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(16)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:red;")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.lineEdit_buscar = QtWidgets.QLineEdit(self.page_tres)
        self.lineEdit_buscar.setGeometry(QtCore.QRect(10, 110, 470, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_buscar.setFont(font)
        self.lineEdit_buscar.setStyleSheet("\n"
"border-radius:15px;\n"
"\n"
"padding-bottom:3px;\n"
"border:1.5px solid red;\n"
"padding-left: 8px;")
        self.lineEdit_buscar.setObjectName("lineEdit_buscar")
        self.bt_filtrar = QtWidgets.QPushButton(self.page_tres)
        self.bt_filtrar.setGeometry(QtCore.QRect(10, 60, 200, 35))
        self.bt_filtrar.setMinimumSize(QtCore.QSize(200, 35))
        self.bt_filtrar.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(6)
        font.setKerning(True)
        self.bt_filtrar.setFont(font)
        self.bt_filtrar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_filtrar.setAutoFillBackground(False)
        self.bt_filtrar.setStyleSheet("QPushButton#bt_filtrar:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:#505050;\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_filtrar:hover{\n"
"font:50 10pt \"Arial Black\";\n"
"background-color:white;\n"
"\n"
"}\n"
"QPushButton#bt_filtrar{\n"
"backgroud-color:#505050;\n"
"font:50 10pt \"Arial Black\";\n"
"border-radius:15px;\n"
"border:1.5px solid red;\n"
"color:red;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.bt_filtrar.setIconSize(QtCore.QSize(15, 15))
        self.bt_filtrar.setObjectName("bt_filtrar")
        self.bt_search_files = QtWidgets.QPushButton(self.page_tres)
        self.bt_search_files.setGeometry(QtCore.QRect(220, 60, 200, 35))
        self.bt_search_files.setMinimumSize(QtCore.QSize(200, 35))
        self.bt_search_files.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(6)
        font.setKerning(True)
        self.bt_search_files.setFont(font)
        self.bt_search_files.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_search_files.setAutoFillBackground(False)
        self.bt_search_files.setStyleSheet("QPushButton#bt_search_files:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:#505050;\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_search_files:hover{\n"
"font:50 10pt \"Arial Black\";\n"
"background-color:white;\n"
"\n"
"}\n"
"QPushButton#bt_search_files{\n"
"backgroud-color:#505050;\n"
"font:50 10pt \"Arial Black\";\n"
"border-radius:15px;\n"
"border:1.5px solid red;\n"
"color:red;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.bt_search_files.setIconSize(QtCore.QSize(15, 15))
        self.bt_search_files.setObjectName("bt_search_files")
        self.bt_upload_file = QtWidgets.QPushButton(self.page_tres)
        self.bt_upload_file.setGeometry(QtCore.QRect(430, 60, 200, 35))
        self.bt_upload_file.setStyleSheet("QPushButton#bt_upload_file:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:#505050;\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_upload_file:hover{\n"
"font:50 10pt \"Arial Black\";\n"
"background-color:white;\n"
"\n"
"}\n"
"QPushButton#bt_upload_file{\n"
"backgroud-color:#505050;\n"
"font:50 10pt \"Arial Black\";\n"
"border-radius:15px;\n"
"border:1.5px solid red;\n"
"color:red;\n"
"}\n"
"")
        self.bt_upload_file.setObjectName("bt_upload_file")
        self.stackedWidget_2.addWidget(self.page_tres)
        self.page_uno = QtWidgets.QWidget()
        self.page_uno.setObjectName("page_uno")
        self.label_27 = QtWidgets.QLabel(self.page_uno)
        self.label_27.setGeometry(QtCore.QRect(230, 20, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color:red;")
        self.label_27.setObjectName("label_27")
        self.lineEdit_descargar_lista = QtWidgets.QLineEdit(self.page_uno)
        self.lineEdit_descargar_lista.setGeometry(QtCore.QRect(70, 80, 531, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_descargar_lista.setFont(font)
        self.lineEdit_descargar_lista.setStyleSheet("border-radius:15px;\n"
"\n"
"padding-bottom:3px;\n"
"border:1.5px solid red;\n"
"padding-left: 8px;")
        self.lineEdit_descargar_lista.setObjectName("lineEdit_descargar_lista")
        self.label_28 = QtWidgets.QLabel(self.page_uno)
        self.label_28.setGeometry(QtCore.QRect(250, 150, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color:red;")
        self.label_28.setObjectName("label_28")
        self.download_LIST = QtWidgets.QPushButton(self.page_uno)
        self.download_LIST.setGeometry(QtCore.QRect(230, 250, 211, 31))
        self.download_LIST.setStyleSheet("QPushButton#download_LIST:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:#505050;\n"
"\n"
"}\n"
"\n"
"QPushButton#download_LIST:hover{\n"
"font:87 10pt \"Arial Black\";\n"
"background-color:white;\n"
"\n"
"}\n"
"QPushButton#download_LIST{\n"
"backgroud-color:#505050;\n"
"font:87 10pt \"Arial Black\";\n"
"border-radius:15px;\n"
"border:1.5px solid red;\n"
"color:red;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.download_LIST.setObjectName("download_LIST")
        self.comboBox = QtWidgets.QComboBox(self.page_uno)
        self.comboBox.setGeometry(QtCore.QRect(210, 200, 261, 31))
        self.comboBox.setStyleSheet("QComboBox {\n"
"                font: 16px;\n"
"                color: #555555;\n"
"                border: 2px solid red;\n"
"                border-radius: 8px;\n"
"                padding: 5px;\n"
"            }\n"
"QComboBox:hover {\n"
"                border-color:red;\n"
"            }\n"
"            \n"
"QComboBox::drop-down {\n"
"                subcontrol-origin: padding;\n"
"                subcontrol-position: top right;\n"
"                width: 25px;\n"
"                border-left-width: 0px;\n"
"                border-top-width: 0px;\n"
"                border-bottom-width: 0px;\n"
"                border-right-width: 0px;\n"
"                border-color: black;\n"
"                border-style: solid;\n"
"                border-radius: 8px;\n"
"            }\n"
"            \n"
"QComboBox::down-arrow {\n"
"               \n"
"                width: 16px;\n"
"                height: 16px;\n"
"            }\n"
"            \n"
"QComboBox::down-button {\n"
"                border: 2px solid #888888;\n"
"                border-radius: 8px;\n"
"                padding: 5px;\n"
"                background-color: #eeeeee;\n"
"            }\n"
"            \n"
"QComboBox::up-button {\n"
"                border: 2px solid #888888;\n"
"                border-radius: 8px;\n"
"                padding: 5px;\n"
"                background-color: #eeeeee;\n"
"            }\n"
"            \n"
"QComboBox:disabled {\n"
"                color: black;\n"
"            }            \n"
"")
        self.comboBox.setEditable(False)
        self.comboBox.setMaxVisibleItems(10)
        self.comboBox.setObjectName("comboBox")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("modules/images/row_combo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon9, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        


        self.comboBox2 = QtWidgets.QComboBox(self.page_tres)
        self.comboBox2.setGeometry(QtCore.QRect(490, 110, 135, 31))
        self.comboBox2.setStyleSheet("QComboBox {\n"
"                font: 16px;\n"
"                color: #555555;\n"
"                border: 2px solid red;\n"
"                border-radius: 8px;\n"
"                padding: 5px;\n"
"            }\n"
"QComboBox:hover {\n"
"                border-color:red;\n"
"            }\n"
"            \n"
"QComboBox::drop-down {\n"
"                subcontrol-origin: padding;\n"
"                subcontrol-position: top right;\n"
"                width: 25px;\n"
"                border-left-width: 0px;\n"
"                border-top-width: 0px;\n"
"                border-bottom-width: 0px;\n"
"                border-right-width: 0px;\n"
"                border-color: black;\n"
"                border-style: solid;\n"
"                border-radius: 8px;\n"
"            }\n"
"            \n"
"QComboBox::down-arrow {\n"
"               \n"
"                width: 16px;\n"
"                height: 16px;\n"
"            }\n"
"            \n"
"QComboBox::down-button {\n"
"                border: 2px solid #888888;\n"
"                border-radius: 8px;\n"
"                padding: 5px;\n"
"                background-color: #eeeeee;\n"
"            }\n"
"            \n"
"QComboBox::up-button {\n"
"                border: 2px solid #888888;\n"
"                border-radius: 8px;\n"
"                padding: 5px;\n"
"                background-color: #eeeeee;\n"
"            }\n"
"            \n"
"QComboBox:disabled {\n"
"                color: black;\n"
"            }            \n"
"")
        self.comboBox2.setEditable(False)
        self.comboBox2.setMaxVisibleItems(10)
        self.comboBox2.setObjectName("comboBox2")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("modules/images/row_combo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox2.addItem(icon9, "")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")





        self.stackedWidget_2.addWidget(self.page_uno)
        self.page_dos = QtWidgets.QWidget()
        self.page_dos.setObjectName("page_dos")
        self.label_29 = QtWidgets.QLabel(self.page_dos)
        self.label_29.setGeometry(QtCore.QRect(180, 80, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color:red;")
        self.label_29.setObjectName("label_29")
        self.lineEdit_buscar_2 = QtWidgets.QLineEdit(self.page_dos)
        self.lineEdit_buscar_2.setGeometry(QtCore.QRect(150, 150, 341, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_buscar_2.setFont(font)
        self.lineEdit_buscar_2.setStyleSheet("border-radius:15px;\n"
"padding-bottom:3px;\n"
"border:1.5px solid red;\n"
"padding-left: 8px;")
        self.lineEdit_buscar_2.setObjectName("lineEdit_buscar_2")
        self.bt_filtrar_2 = QtWidgets.QPushButton(self.page_dos)
        self.bt_filtrar_2.setGeometry(QtCore.QRect(230, 240, 141, 31))
        self.bt_filtrar_2.setStyleSheet("QPushButton#bt_filtrar_2:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:#505050;\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_filtrar_2:hover{\n"
"font:87 10pt \"Arial Black\";\n"
"background-color:white;\n"
"\n"
"}\n"
"QPushButton#bt_filtrar_2{\n"
"backgroud-color:#505050;\n"
"font:87 10pt \"Arial Black\";\n"
"border-radius:15px;\n"
"color:red;\n"
"border:1.5px solid red;\n"
"}")
        self.bt_filtrar_2.setObjectName("bt_filtrar_2")
        self.progressBar_2 = QtWidgets.QProgressBar(self.page_dos)
        self.progressBar_2.setGeometry(QtCore.QRect(100, 370, 411, 31))
        self.progressBar_2.setStyleSheet("QProgressBar {\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #FFDAB9, stop:1 #CD5C5C);\n"
"    border-radius: 5px;\n"
"}")
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.search_files = QtWidgets.QPushButton(self.page_dos)
        self.search_files.setGeometry(QtCore.QRect(60, 240, 141, 31))
        self.search_files.setStyleSheet("QPushButton#search_files:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"border-color:red;\n"
"background-color:#505050;\n"
"\n"
"}\n"
"\n"
"QPushButton#search_files:hover{\n"
"font:87 10pt \"Arial Black\";\n"
"background-color:white;\n"
"\n"
"}\n"
"QPushButton#search_files{\n"
"backgroud-color:#505050;\n"
"font:87 10pt \"Arial Black\";\n"
"border-radius:15px;\n"
"border-color:red;\n"
"color:red;\n"
"border:1.5px solid red;\n"
"}\n"
"\n"
"")
        self.search_files.setObjectName("search_files")
        self.bt_stop = QtWidgets.QPushButton(self.page_dos)
        self.bt_stop.setGeometry(QtCore.QRect(400, 240, 141, 31))
        self.bt_stop.setStyleSheet("QPushButton#bt_stop:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:#505050;\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_stop:hover{\n"
"font:87 10pt \"Arial Black\";\n"
"background-color:white;\n"
"\n"
"}\n"
"QPushButton#bt_stop{\n"
"backgroud-color:#505050;\n"
"font:87 10pt \"Arial Black\";\n"
"border-radius:15px;\n"
"border:1.5px solid red;\n"
"color:red;\n"
"}")
        self.bt_stop.setObjectName("bt_stop")
        self.stackedWidget_2.addWidget(self.page_dos)
        self.page_cuatro = QtWidgets.QWidget()
        self.page_cuatro.setObjectName("page_cuatro")
        self.label_15 = QtWidgets.QLabel(self.page_cuatro)
        self.label_15.setGeometry(QtCore.QRect(20, 250, 541, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.lineEdit_site_Sharepoint = QtWidgets.QLineEdit(self.page_cuatro)
        self.lineEdit_site_Sharepoint.setGeometry(QtCore.QRect(20, 100, 280, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_site_Sharepoint.setFont(font)
        self.lineEdit_site_Sharepoint.setStyleSheet("\n"
"border-radius:15px;\n"
"\n"
"padding-bottom:3px;\n"
"border:1.5px solid red;\n"
"padding-left: 8px;")
        self.lineEdit_site_Sharepoint.setObjectName("lineEdit_site_Sharepoint")
        self.lineEdit_folder_subir_archivo = QtWidgets.QLineEdit(self.page_cuatro)
        self.lineEdit_folder_subir_archivo.setGeometry(QtCore.QRect(20, 340, 280, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_folder_subir_archivo.setFont(font)
        self.lineEdit_folder_subir_archivo.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_folder_subir_archivo.setStyleSheet("border-radius:15px;\n"
"\n"
"padding-bottom:3px;\n"
"border:1.5px solid red;\n"
"padding-left: 8px;")
        self.lineEdit_folder_subir_archivo.setObjectName("lineEdit_folder_subir_archivo")
        self.lineEdit_Path_lists = QtWidgets.QLineEdit(self.page_cuatro)
        self.lineEdit_Path_lists.setGeometry(QtCore.QRect(20, 200, 280, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_Path_lists.setFont(font)
        self.lineEdit_Path_lists.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_Path_lists.setStyleSheet("border-radius:15px;\n"
"\n"
"padding-bottom:3px;\n"
"border:1.5px solid red;\n"
"padding-left: 8px;")
        self.lineEdit_Path_lists.setObjectName("lineEdit_Path_lists")
        self.bt_save_con = QtWidgets.QPushButton(self.page_cuatro)
        self.bt_save_con.setGeometry(QtCore.QRect(20, 440, 200, 35))
        self.bt_save_con.setMinimumSize(QtCore.QSize(200, 35))
        self.bt_save_con.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        font.setKerning(True)
        self.bt_save_con.setFont(font)
        self.bt_save_con.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_save_con.setAutoFillBackground(False)
        self.bt_save_con.setStyleSheet("QPushButton#bt_save_con:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:#505050;\n"
"\n"
"}\n"
"\n"
"QPushButton#bt_save_con:hover{\n"
"font:87 10pt \"Arial Black\";\n"
"background-color:white;\n"
"\n"
"}\n"
"QPushButton#bt_save_con{\n"
"backgroud-color:#505050;\n"
"font:87 10pt \"Arial Black\";\n"
"border-radius:15px;\n"
"border:1.5px solid red;\n"
"color:red;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.bt_save_con.setIconSize(QtCore.QSize(15, 15))
        self.bt_save_con.setObjectName("bt_save_con")
        self.label_16 = QtWidgets.QLabel(self.page_cuatro)
        self.label_16.setGeometry(QtCore.QRect(20, 20, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color:red;")
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.page_cuatro)
        self.label_18.setGeometry(QtCore.QRect(20, 150, 461, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.stackedWidget_2.addWidget(self.page_cuatro)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        #self.bt_menu.setText(_translate("MainWindow", "MENU"))
        self.bt_inicio.setText(_translate("MainWindow", "INICIO"))
        self.bt_base_datos.setText(_translate("MainWindow", "SUBIR LISTA"))
        self.bt_list.setText(_translate("MainWindow", "DESCARGA LISTA"))
        self.bt_config.setText(_translate("MainWindow", "Configuraciones"))
        self.label_21.setText(_translate("MainWindow", "DESPUES"))
        self.label_22.setText(_translate("MainWindow", "COS"))
        self.label_23.setText(_translate("MainWindow", "DAAS"))
        self.label_17.setText(_translate("MainWindow", "ANTES"))
        self.label_19.setText(_translate("MainWindow", "DISEÑO NODOS"))
        self.lineEdit_buscar.setPlaceholderText(_translate("MainWindow", "BUSCAR NODO"))
        self.bt_filtrar.setText(_translate("MainWindow", "Filtrar"))
        self.bt_search_files.setText(_translate("MainWindow", "Buscar archivos"))
        self.bt_upload_file.setText(_translate("MainWindow", "Subir Diseño"))
        self.label_27.setText(_translate("MainWindow", "DESCARGA DE LISTAS"))
        self.lineEdit_descargar_lista.setPlaceholderText(_translate("MainWindow", "LISTA A DESCARGAR"))
        self.label_28.setText(_translate("MainWindow", "GUARDAR COMO:"))
        self.download_LIST.setText(_translate("MainWindow", "Descargar lista"))
        self.comboBox.setCurrentText(_translate("MainWindow", "Elija nombre del archivo"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Elija nombre del archivo"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Arris_SCMSummary"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Casa_SCMSummary"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Ocupacion- RPHY Harmonic_DAAS"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Ocupacion-Harmonic_COS"))
        #self.comboBox2.setCurrentText(_translate("MainWindow", "nodo"))
        self.comboBox2.setItemText(0, _translate("MainWindow", "Tipo nodo"))
        self.comboBox2.setItemText(1, _translate("MainWindow", "1 x 2"))
        self.comboBox2.setItemText(2, _translate("MainWindow", "2 x 4"))
        self.label_29.setText(_translate("MainWindow", "SUBIR LISTA A SHAREPOINT"))
        self.lineEdit_buscar_2.setPlaceholderText(_translate("MainWindow", "NOMBRE DE LISTA DE SHAREPOINT"))
        self.bt_filtrar_2.setText(_translate("MainWindow", "SUBIR"))
        self.search_files.setText(_translate("MainWindow", "BUSCAR ARCHIVO"))
        self.bt_stop.setText(_translate("MainWindow", "DETENER"))
        self.label_15.setText(_translate("MainWindow", "Adicione una vez mas este caracter \'\\\' , a la ruta como este ejemplo: C:-->\\\\<--Users\\PC\\Desktop"))
        self.lineEdit_site_Sharepoint.setPlaceholderText(_translate("MainWindow", "Link del sitio de Sharepoint"))
        self.lineEdit_folder_subir_archivo.setPlaceholderText(_translate("MainWindow", "Ruta de carpeta a subir en Sharepoint"))
        self.lineEdit_Path_lists.setPlaceholderText(_translate("MainWindow", "Ruta para la descarga de listas"))
        self.bt_save_con.setText(_translate("MainWindow", "Guardar"))
        self.label_16.setText(_translate("MainWindow", "CONFIGURACION"))
        self.label_18.setText(_translate("MainWindow", "Ejemplo: https://claromovilco.sharepoint.com/sites/nombre_sitio_SharePoint/\" "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
