# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'combobox_names_files.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog


class Ui_Form(QDialog):

    def __init__(self):
        super().__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(400, 300)
        self.comboBox = QtWidgets.QComboBox(self)
        self.comboBox.setGeometry(QtCore.QRect(100, 80, 211, 31))
        self.comboBox.setObjectName("comboBox")
        self.setWindowTitle(("Form"))
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0,(""))
        self.comboBox.setItemText(1,("Arris_SCMSummary"))
        self.comboBox.setItemText(2,("Casa_SCMSummary"))
        self.comboBox.setItemText(3,("Ocupacion - Marcacion RPHY Harmonic"))      
        QtCore.QMetaObject.connectSlotsByName(self)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_Form()
    ui.show()
    sys.exit(app.exec_())
        

        
