# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Barra_descaga_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget,QDialog

import download_lists
import time
import threading
from download_lists import download_list
from office365_api import SharePoint
########
FOLDER_DEST="C:\\Users\\IC0167A\\Desktop\\Proyecto_final\\Descargas"
FILE_NAME="PRUEBA4"
EXPORT_TYPE='Excel'
LIST_NAME="PRUEBA_17"
file_name=download_lists.Type_file(FILE_NAME,EXPORT_TYPE)
########

class Ui_Descarga_Listas(QDialog):
    def __init__(self):
        super().__init__()
        self.setModal(True)
        self.setupUi()


    def setupUi(self):
        self.setGeometry(100,100,329,142)
        self.setWindowTitle("Descarga Listas")
        self.resize(329, 142)
        self.Label_descarga_list = QtWidgets.QLabel(self)
        self.Label_descarga_list.setGeometry(QtCore.QRect(110, 30, 111, 16))
        self.Label_descarga_list.setObjectName("Label_descarga_list")
        self.progressBar = QtWidgets.QProgressBar(self)
        self.progressBar.setGeometry(QtCore.QRect(0, 60, 331, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(10, 100, 311, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.download_LIST)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Descarga_Listas):
        _translate = QtCore.QCoreApplication.translate
        Descarga_Listas.setWindowTitle(_translate("Descarga_Listas", "Descargando"))
        self.Label_descarga_list.setText(_translate("Descarga_Listas", "Descargando archivo..."))
        self.pushButton.setText(_translate("Descarga_Listas", "Descargar lista"))

    def download_LIST(self):
        time.time.s
        self.downloader_thread = threading.Thread(target=download_lists.download_list(LIST_NAME,EXPORT_TYPE,FOLDER_DEST,file_name))
'''        sp_list=SharePoint().get_list(LIST_NAME)
        total_items=len(sp_list)
        tiempo=round(1/total_items*100,0)
        for i,item in enumerate(sp_list):
            progress=((i + 1) / total_items * 100)
            time.sleep(tiempo)
            self.progressBar.setValue(progress)'''
        
        
        



