# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prueba_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(948, 398)
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(840, -10, 271, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/claro.jpg"))
        self.label.setObjectName("label")
        self.btn_buscar = QtWidgets.QPushButton(Form)
        self.btn_buscar.setGeometry(QtCore.QRect(290, 70, 75, 23))
        self.btn_buscar.setObjectName("btn_buscar")
        self.btn_download_list=QtWidgets.QPushButton(Form)
        self.btn_download_list.setGeometry(QtCore.QRect(550,70,75,23))
        self.btn_download_list.setObjectName("btn_download_list")
        self.tabla = QtWidgets.QTableWidget(Form)
        self.tabla.setGeometry(QtCore.QRect(10, 170, 461, 192))
        self.tabla.setObjectName("tabla")
        self.tabla.setColumnCount(0)
        self.tabla.setRowCount(0)
        self.text2 = QtWidgets.QLabel(Form)
        self.text2.setGeometry(QtCore.QRect(20, 70, 91, 16))
        self.text2.setObjectName("text2")
        self.text1 = QtWidgets.QLabel(Form)
        self.text1.setGeometry(QtCore.QRect(370, 0, 221, 71))
        self.text1.setObjectName("text1")
        self.busqueda = QtWidgets.QLineEdit(Form)
        self.busqueda.setGeometry(QtCore.QRect(90, 70, 151, 20))
        self.busqueda.setObjectName("busqueda")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(420, 70, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(490, 170, 451, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(190, 140, 81, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(660, 140, 91, 31))
        self.label_3.setObjectName("label_3")

        Form.setCentralWidget(self.centralwidget)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_buscar.setText(_translate("Form", "Buscar"))
        self.btn_download_list.setText(_translate("Form","Lista"))
        self.text2.setText(_translate("Form", "Busqueda:"))
        self.text1.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">Bienvendio</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "Archivo"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Antes</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Después</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
