# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5.QtWidgets import (QApplication,QLabel,QWidget,QLineEdit,QPushButton,QMessageBox,QCheckBox)
from PyQt5.QtGui import QFont,QPixmap
from PyQt5.QtWidgets import (QDialog,QLabel,QPushButton,QLineEdit,QMessageBox,)
from main import MiApp
from Config_User import ConfigUsuarioView
from dotenv import set_key,dotenv_values
from Login_Final import*
from search_files import*
class Login(QWidget):
        def __init__(self):
            super().__init__()
            self.ui=Ui_Form()
            self.ui.setupUi(self)
            self.ui.Login_button.clicked.connect(self.login) 
             #*Button Config
            self.ui.Config_button.clicked.connect(self.config_usuario)
            self.ui.Close_button.clicked.connect(self.control_close)
             #Label de usuario
            self.is_loged=False
            self.ui.lineEdit_2.setEchoMode(
                  QLineEdit.EchoMode.Password
             )
            
             #Checkbox para poder visualizar o no, la contraseña
            self.ui.checkBox.toggled.connect(self.mostrar_pass)

        def control_close(self):#*Función para cerrar el programa
            self.close()

        def mostrar_pass(self,clicked):
                  if clicked :
                    self.ui.lineEdit_2.setEchoMode(
                        QLineEdit.EchoMode.Normal
                    )           
                  else:
                        self.ui.lineEdit_2.setEchoMode(
                        QLineEdit.EchoMode.Password
                    )          
                  
        def login(self):
                  users=[]
                  user_path='usuarios.txt'

                  try:
                    with open(user_path,'r') as f:
                          for linea in f:
                            users.append(linea.strip("\n"))
                    login_information=f"{self.ui.lineEdit.text()},{self.ui.lineEdit_2.text()}"
                    Username=self.ui.lineEdit.text()
                    Password=self.ui.lineEdit_2.text()
                    print(f'Correo==>{Username}')
                    print(f'Pass==>{Password}')
                    env=dotenv_values(".env")
                    set_key(".env","sharepoint_email",Username)#input("Digite correo==>") cambiar por la variable del qt
                    USERNAME=env["sharepoint_email"]
                    set_key(".env","sharepoint_password",Password)#
                    PASSWORD=env["sharepoint_password"]
                    if login_information in users:
                         QMessageBox.information(self,"Inicio sesion",
                         "Inicio sesion exitoso",
                         QMessageBox.StandardButton.Ok,
                         QMessageBox.StandardButton.Ok)
                         self.is_loged=True
                         self.close()
                         self.open_main()
                    else:
                         QMessageBox.warning(self,"Error Message",
                         "Credenciales incorrectas",
                         QMessageBox.StandardButton.Close,
                         QMessageBox.StandardButton.Close)
                  except FileNotFoundError as e: 
                         QMessageBox.warning(self,"Error Message",
                         f"Base de datos de usuario no encontrada: {e}",
                         QMessageBox.StandardButton.Close,
                         QMessageBox.StandardButton.Close)
                  except Exception as u:
                          QMessageBox.warning(self, "Error Message",
                         f'Error en el servidor: {u}',
                         QMessageBox.StandardButton.Close,
                         QMessageBox.StandardButton.Close)
        def open_main(self):
              self.main= MiApp()
              self.main.show()
        def config_usuario(self):
            self.configu_user=ConfigUsuarioView()
            self.configu_user.show()


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    Log= Login()
    Log.show()
    sys.exit(app.exec_())
